language: ruby
rvm:
- 2.3.3

script: bundle exec jekyll build

branches:
  only:
  - master

sudo: false

after_success: >
  if [[ "${TRAVIS_PULL_REQUEST:-unknown}" == "false" && $TRAVIS_BRANCH == master ]] ; then
    pushd _site
    find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} $FTP_HOST/{} \;
    popd
  fi