language: ruby
rvm:
- 2.3.3

script: bundle exec jekyll build

branches:
  only:
  - master

sudo: false

after_success: >
  if [[ "${TRAVIS_PULL_REQUEST:-unknown}" == "false" && $TRAVIS_BRANCH == master ]] ; then
    curl --ftp-create-dirs -T _site/* -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
  fi