language: ruby
rvm:
- 2.3.3

script: bundle exec jekyll build

branches:
  only:
  - master

sudo: false

after_success: >
  if [[ "${TRAVIS_PULL_REQUEST:-unknown}" == "false" && $TRAVIS_BRANCH == master ]] ; then
    pushd _site
    echo "${SSH_KEY}" | base64 --decode >/tmp/sftp_rsa
    scp -o 'StrictHostKeyChecking no' -B -r -P $FTP_PORT ./* $FTP_USER@$FTP_HOST:~/$FTP_PATH
    popd
  fi
