title: TeaVM
email: info@teavm.org
description: >
  A Java bytecode to JavaScript translator.

baseurl: ""
url: http://teavm.org
git_address: https://github.com/konsoletyper/teavm
git_edit_address: https://github.com/konsoletyper/teavm-site/edit/master
forum_address: https://groups.google.com/forum/#!forum/teavm
issue_tracker: https://github.com/konsoletyper/teavm/issues

bootwatch: readable

teavm_version: 0.5.1
flavour_version: 0.1.0
teavm_branch: 0.5.x

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - serve.sh
  - LICENSE
  - vendor

timezone: Europe/Moscow
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs

collections:
  docs:
    permalink: /:collection/:path.html
    output: true
